# Generated by Django 3.2.13 on 2022-06-26 08:28
import djongo.models.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ML',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(
                    auto_created=True, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('file_path', models.URLField()),
                ('file_size', models.IntegerField(default=0)),
                ('version', models.IntegerField(unique=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'file_model',
            },
        ),
    ]
