# Generated by Django 3.1.12 on 2022-08-24 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ml',
            name='version',
        ),
    ]
