# Generated by Django 3.1.12 on 2022-08-24 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ml', '0002_remove_ml_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ml',
            old_name='_id',
            new_name='id',
        ),
    ]
