# Generated by Django 3.1.12 on 2022-08-24 07:00

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('xmin', models.FloatField()),
                ('xmax', models.FloatField()),
                ('ymin', models.FloatField()),
                ('ymax', models.FloatField()),
                ('label', models.CharField(max_length=50, verbose_name='Image Label')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('img_url', models.CharField(max_length=200, verbose_name='url')),
                ('img_name', models.CharField(max_length=50, verbose_name='name')),
                ('img_size', models.IntegerField()),
                ('img_dimension', djongo.models.fields.JSONField()),
                ('annotations', djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='objects.annotation')),
            ],
            options={
                'db_table': 'objects',
            },
        ),
    ]
