# Generated by Django 3.2.12 on 2022-08-14 14:19

import api.objects.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('coordinates', djongo.models.fields.ArrayField(model_container=api.objects.models.Coordinate)),
                ('label', models.CharField(max_length=50, verbose_name='Image Label')),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('img_url', models.CharField(max_length=200, verbose_name='url')),
                ('img_name', models.CharField(max_length=50, verbose_name='name')),
                ('img_size', models.IntegerField()),
                ('img_dimension', djongo.models.fields.JSONField()),
                ('annotations', djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='objects.annotation')),
            ],
            options={
                'db_table': 'objects',
            },
        ),
    ]
