# Generated by Django 3.2.14 on 2022-08-14 11:49

import api.objects.models
from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('objects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('coordinates', djongo.models.fields.ArrayField(model_container=api.objects.models.Coordinate)),
                ('label', models.CharField(max_length=50, verbose_name='Image Label')),
            ],
        ),
        migrations.RenameField(
            model_name='object',
            old_name='_id',
            new_name='id',
        ),
        migrations.AddField(
            model_name='object',
            name='annotations',
            field=djongo.models.fields.ArrayReferenceField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='annotations', to='objects.annotation'),
        ),
    ]
